subscription:
  enabled: true
  apiVersion: operators.coreos.com/v1alpha1
  name: keycloak
  namespace: keycloak
  channel: v5
  source: operatorhubio-catalog
  sourceNamespace: olm
  createNamespace: true
  createOperatorGroup: true
  targetNamespaces:
    - "keycloak"

operatorResource:
  enabled: true
  validateSpec: false
  strictValidation: false
  apiVersion: k8s.keycloak.org/v2alpha1
  kind: Keycloak
  name: "keycloak"
  namespace: "keycloak"
  createNamespace: true
  spec:
    instances: 1
    hostname:
      hostname: sso.cloudastro.io
      admin: sso.cloudastro.io/admin
      strict: false
      backchannelDynamic: true
    http:
      httpEnabled: false
      httpsPort: 8443
      tlsSecret: keycloak-tls-secret

    db:
      vendor: postgres
      host: postgresql.keycloak.svc.cluster.local
      database: keycloak
      port: 5432
      schema: public
      poolInitialSize: 30
      poolMinSize: 30
      poolMaxSize: 50
      usernameSecret:
        name: keycloak-db-secret
        key: username
      passwordSecret:
        name: keycloak-db-secret
        key: password

    resources:
      requests:
        cpu: 100
        memory: "100Mi"
      limits:
        cpu: "1"
        memory: "2000Mi"

    # Production features
    features:
      enabled:
        - multi-site # For cross-datacenter replication
        - authorization # Fine-grained authorization
        - account3 # New account console
        - admin-fine-grained-authz # Admin fine-grained authorization
        - declarative-user-profile # Declarative user profile
        - docker # Docker registry authentication
        - token-exchange # Token exchange
        - recovery-codes # Account recovery codes
        - scripts # JavaScript providers
        - preview # Preview features
      disabled:
        - step-up-authentication # Disable if not needed

    # Production optimizations and monitoring
    additionalOptions:
      # Logging configuration
      - name: log-console-output
        value: json
      - name: log-level
        value: INFO

      # Metrics and monitoring
      - name: metrics-enabled
        value: "true"
      - name: health-enabled
        value: "true"
      - name: event-metrics-user-enabled
        value: "true"

      # Performance optimizations
      - name: cache-stack
        value: kubernetes
      - name: proxy-headers
        value: forwarded|xforwarded

      # Security settings
      - name: spi-sticky-session-encoder-infinispan-should-attach-route
        value: "false"
      - name: spi-login-recaptcha-site-key
        secret:
          name: keycloak-recaptcha-secret
          key: site-key
      - name: spi-login-recaptcha-secret-key
        secret:
          name: keycloak-recaptcha-secret
          key: secret-key

    transaction:
      xaEnabled: false
    update:
      strategy: Auto
    startOptimized: true # Use optimized startup for production
