apiVersion: v2
name: cert-manager
description: A Helm chart for cert-manager
home: https://cert-manager.io
icon: https://raw.githubusercontent.com/cert-manager/community/4d35a69437d21b76322157e6284be4cd64e6d2b7/logo/logo-small.png
keywords:
  - cert-manager
  - kube-lego
  - letsencrypt
  - tls
sources:
  - https://github.com/cert-manager/cert-manager
version: 0.1.0
appVersion: v1.18.2
dependencies:
  - repository: oci://quay.io/jetstack/charts/cert-manager
    name: cert-manager
    version: 1.18.2
