apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-green
  labels:
    app: test-app
    track: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      track: green
  template:
    metadata:
      labels:
        app: myapp
        track: green
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo:latest
        args: ["-text", "version: v2"]
        ports:
        - containerPort: 5678
        readinessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 2
          periodSeconds: 2
