# Number of replicas per deployment
replicaCount: 2

fullnameOverride: kosict-demo


image:
  repository: njomzaismaili/kosict-demo
  tag: blue          
  pullPolicy: IfNotPresent



service:
  port: 80                  


blue:
  fullnameOverride: kosict-demo
  enabled: true
  image:
    tag: blue             
  containerPort: 8080    
  servicePort: 80  


green:
  fullnameOverride: kosict-demo
  enabled: true
  image:
    tag: green               
  containerPort: 9090      
  servicePort: 80           

ingress:
  enabled: true
  className: nginx
  host: demo.cloudastro.de
  weights:
    blue: 90                
    green: 10              

resources:
  requests:
    cpu: 250m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

env: []
# Example:
# env:
#   - name: ENVIRONMENT
#     value: "production"


nodeSelector: {}
tolerations: []
affinity: {}
