replicaCount: 2

image:
  tag: "1.27.0-alpine"
  pullPolicy: IfNotPresent

html:
  content: "app-a-qa"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: app-a-qa.example.com
      paths:
        - path: /
          pathType: Prefix
