apiVersion: v2
name: openbao
version: 0.1.0
appVersion: v2.4.1
description: Official OpenBao Chart
icon: https://github.com/openbao/artwork/blob/main/color/openbao-color.svg
keywords:
  [
    "vault",
    "openbao",
    "security",
    "encryption",
    "secrets",
    "management",
    "automation",
    "infrastructure",
  ]
dependencies:
  - name: openbao
    version: 0.18.2
    repository: https://openbao.github.io/openbao-helm