image:
  tag: "1.27.0-alpine"

html:
  content: "app-a-prod"

replicaCount: 1

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: true
  hosts:
    - host: app-a.example.com
      paths:
        - path: /
          pathType: Prefix
