image:
  tag: "1.27.0"

html:
  content: "app-a-prod"

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: app-a.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: app-a-tls
      hosts:
        - app-a.example.com
