global:
  env: dev
  projectName: kosict
  source:
    repoURL: "https://github.com/CloudAstro/KOSICT-demo.git"
    targetRevision: main
  namespaceLabels:
    secret-inject: "true"

# apps:
#   app-a:
#     enabled: true
#     syncOptions:
#       - PruneLast=true
#       - ServerSideApply=true
#     retry:
#       limit: 5
#       backoff:
#         duration: 5s
#         factor: 2
#         maxDuration: 3m
#     revisionHistoryLimit: 3
#     dev:
#       helmValues:
#         replicaCount: 1
#     qa:
#       helmValues:
#         replicaCount: 2
#     prod:
#       helmValues:
#         replicaCount: 3
#   app-b:
#     enabled: true
#     syncOptions:
#       - PruneLast=true
#       - ServerSideApply=true
#     retry:
#       limit: 5
#       backoff:
#         duration: 5s
#         factor: 2
#         maxDuration: 3m
#     revisionHistoryLimit: 3
#     dev:
#       helmValues:
#     qa:
#       helmValues:
#     prod:
#       helmValues:
#   app-c:
#     enabled: true
#     syncOptions:
#       - PruneLast=true
#       - ServerSideApply=true
#     retry:
#       limit: 5
#       backoff:
#         duration: 5s
#         factor: 2
#         maxDuration: 3m
#     revisionHistoryLimit: 3
#     dev: 
#       helmValues:
#         postgresql.password: vault:secret/data/kosict/app-c/dev#password
#     qa:
#       helmValues:
#         postgresql.password: vault:secret/data/kosict/app-c/qa#password
#     prod:
#       helmValues:
#         postgresql.password: vault:secret/data/kosict/app-c/prod#password
