global:
  env: dev
  projectName: kosict
  source:
    repoURL: "https://github.com/CloudAstro/KOSICT-demo.git"
    targetRevision: main

apps:
  app-a:
    enabled: true
    dev:
      helmValues:
    qa:
      helmValues:
    prod:
      helmValues:
  app-b:
    enabled: true
    dev:
      helmValues:
    qa:
      helmValues:
    prod:
      helmValues:
  app-c:
    enabled: true
    dev:
      helmValues:
    qa:
      helmValues:
    prod:
      helmValues:
