apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-a.fullname" . }}-html
  labels:
    {{- include "app-a.labels" . | nindent 4 }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>{{ .Values.html.content }}</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
                margin: 0;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            }
            .container {
                text-align: center;
                background: white;
                padding: 50px;
                border-radius: 10px;
                box-shadow: 0 10px 40px rgba(0,0,0,0.2);
            }
            h1 {
                color: #333;
                font-size: 48px;
                margin: 0;
            }
            p {
                color: #666;
                font-size: 24px;
                margin-top: 20px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>{{ .Values.html.content }}</h1>
            <p>Application: {{ .Release.Name }}</p>
            <p>Chart: {{ .Chart.Name }} v{{ .Chart.Version }}</p>
        </div>
    </body>
    </html>
