# Override ONLY dev-specific values
image:
  tag: "1.27.0-alpine"
  pullPolicy: Always

html:
  content: "app-a-dev"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

ingress:
  enabled: true
  hosts:
    - host: app-a-dev.example.com
      paths:
        - path: /
          pathType: Prefix
