{{- if .Values.ingress.enabled }}

# --- Primary (stable) Ingress ---
{{- if .Values.ingress.stable.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mychart.fullname" . }}-stable
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
{{- if .Values.ingress.stable.annotations }}
{{ toYaml .Values.ingress.stable.annotations | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.stable.path }}
        pathType: {{ .Values.ingress.stable.pathType }}
        backend:
          service:
            name: {{ include "mychart.fullname" . }}-stable
            port:
              number: {{ .Values.stable.servicePort }}
{{- end }}

---

# --- Canary (canary) Ingress ---
{{- if .Values.ingress.canary.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mychart.fullname" . }}-canary
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "{{ .Values.ingress.Canary.weight }}"
{{- if .Values.ingress.canary.annotations }}
{{ toYaml .Values.ingress.canary.annotations | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.canary.path }}
        pathType: {{ .Values.ingress.canary.pathType }}
        backend:
          service:
            name: {{ include "mychart.fullname" . }}-canary
            port:
              number: {{ .Values.canary.servicePort }}
{{- end }}
{{- end }}
