{{- if .Values.storageClasses }}
{{- range $index, $sc := .Values.storageClasses }}
{{- if ne $sc.enabled false }}
{{- if $index }}
---
{{- end }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $sc.name }}
  {{- if or $sc.labels ($.Values.global).labels }}
  labels:
    {{- if $sc.labels }}
    {{- range $key, $value := $sc.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
    {{- if and ($.Values.global) ($.Values.global.labels) }}
    {{- range $key, $value := $.Values.global.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
  {{- end }}
  {{- if or $sc.annotations $sc.isDefault }}
  annotations:
    {{- if $sc.isDefault }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
    {{- if $sc.annotations }}
    {{- range $key, $value := $sc.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  {{- end }}
provisioner: {{ $sc.provisioner }}
{{- if $sc.parameters }}
parameters:
  {{- range $key, $value := $sc.parameters }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
reclaimPolicy: {{ $sc.reclaimPolicy | default "Delete" }}
allowVolumeExpansion: {{ $sc.allowVolumeExpansion | default false }}
{{- if $sc.mountOptions }}
mountOptions:
{{- range $sc.mountOptions }}
  - {{ . | quote }}
{{- end }}
{{- end }}
volumeBindingMode: {{ $sc.volumeBindingMode | default "Immediate" }}
{{- if $sc.allowedTopologies }}
allowedTopologies:
{{- toYaml $sc.allowedTopologies | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
